language: node_js
node_js:
  - "0.11"
before_install:
  - export DISPLAY=:99.0
script:
  - ./tool/travis.sh
services:
  - postgresql
before_script:
  - psql -c "create user testdb with password 'password';" -U postgres
  - psql -c "create database testdb with owner testdb;" -U postgres

