name: postgresql2
version: 1.7.0+ac
description: >
  A fork of Greg's PostgreSQL driver (xxgreg/postgresql)
  using conserved substitution respecting strings and @@ operators.
  Also optimizing the pool implementation aggressively.
homepage: https://github.com/tomyeh/postgresql
publish_to: https://pub.anycode.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  sasl_scram: ^0.1.1
  convert: ^3.1.1
  charcode: ^1.3.1
  rikulo_commons: ^6.0.1+1

dev_dependencies:
  test: any
  yaml: any
