name: postgresql2
version: 0.3.2
author: Greg Lowe <greg@vis.net.nz>
description: >
  A temporary fork of Greg's PostgreSQL driver (xxgreg/postgresql)
  using conserved substitution respecting strings and @@ operators.
homepage: https://github.com/tomyeh/postgresql
environment:
  sdk: ">=0.8.10+6 <2.0.0"
dependencies:
  crypto: ">=0.9.0 <0.10.0"
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
  yaml: ">=0.9.0 <3.0.0"
