name: postgresql2
version: 1.5.0
description: >
  A fork of Greg's PostgreSQL driver (xxgreg/postgresql)
  using conserved substitution respecting strings and @@ operators.
  Also optimizing the pool implementation aggressivly.
homepage: https://github.com/tomyeh/postgresql

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  crypto: ">=2.0.0"
  convert: ">=1.0.0"
  charcode: ">=1.0.0"
  rikulo_commons: ">=5.0.1"

dev_dependencies:
  test: any
  yaml: any
