name: postgresql2
version: 0.7.7+1
description: >
  A fork of Greg's PostgreSQL driver (xxgreg/postgresql)
  using conserved substitution respecting strings and @@ operators.
  Also optimizing the pool implementation aggressivly.
homepage: https://github.com/tomyeh/postgresql

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  crypto: ">=2.0.0"
  convert: ">=1.0.0"
  charcode: ">=1.0.0"

dev_dependencies:
  test: any
  yaml: any
